#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  points:
    external:
      name: net_points

services:
  cliPointOrg1:
    container_name: cliPointOrg1
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.points.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.points.com/users/Admin@org1.points.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../../application:/opt/gopath/src/github.com/application
        - ./../../configuration:/opt/gopath/src/github.com/configuration
        - ./../../gateway:/opt/gopath/src/github.com/gateway
        - ./../../pscontract:/opt/gopath/src/github.com/pscontract
        - ./../../points-network/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - points
    #depends_on:
    #  - orderer.points.com
    #  - peer0.org1.points.com
    #  - couchdb
